[package]
name = "advent23"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[dependencies]
assert_approx_eq = "1.1.0"
gcd = "2.3.0"
itertools = "0.12.0"
num = "0.4.3"
priority-queue = "1.3.2"
queues = "1.1.0"
